-- begin DMMOCKS_PHONE_SETTINGS
alter table DMMOCKS_PHONE_SETTINGS add constraint FK_DMMOCKS_PHONE_SETTINGS_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_DMMOCKS_PHONE_SETTINGS_ON_USER on DMMOCKS_PHONE_SETTINGS (USER_ID)^
-- end DMMOCKS_PHONE_SETTINGS
